version: "2"

services:
  database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    links:
      - users
      - posts
      - comment
    hostname: database

  users:
    build: users/
    image: willpower/users_service
    restart: always
    hostname: users
    ports:
      - 4001:4001
    volumes:
      - ./users/src:/src

  posts:
    build: posts/
    image: willpower/posts_service
    restart: always
    hostname: posts
    ports:
      - 4002:4002
    volumes:
      - ./posts/src:/src

  comment:
    build: comment/
    image: willpower/comment_service
    restart: always
    hostname: comment
    ports:
      - 4003:4003
    volumes:
      - ./comment/src:/src
